export type RootStackParamList = {
  Splash: undefined;
  MobileEntry: undefined;
  OTPVerification: { mobileNumber: string };
  ConsentPermissions: undefined;
  PANVerification: undefined;
  AadhaarVerification: undefined;
  DigiLockerConnect: undefined;
  SelfieCapture: undefined;
  FaceMatchProcessing: undefined;
  DocumentUpload: undefined;
  AddressVerification: undefined;
  EmploymentDetails: undefined;
  FATCADeclaration: undefined;
  NomineeDetails: undefined;
  SignatureUpload: undefined;
  AuthLanding: undefined;
  Login: undefined;
  SignUp: undefined;
  ForgotPassword: undefined;
  ClientDashboard: undefined;
  ClientTabs: undefined;
  Notifications: undefined;
  Home: undefined;
  Details: { itemId: number };
  Profile: { userId: string };
  SendMoney: undefined;
  SelectPayee: undefined;
};
